# Etapa de construcción
FROM maven:3.9.6-eclipse-temurin-21 AS builder
WORKDIR /app
COPY e2e-tests /app
# Instalar dependencias y compilar
RUN mvn clean compile -q

# Etapa de ejecución
FROM maven:3.9.6-eclipse-temurin-21
WORKDIR /app
COPY --from=builder /app /app

# Instalar curl para healthcheck
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

# Copiar script de entrada
COPY e2e-tests/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Comando por defecto
ENTRYPOINT ["/entrypoint.sh"]
