# SonarQube configuration for python-healthcheck-service
sonar.projectKey=python-healthcheck-service
sonar.projectName=python-healthcheck-service
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=tests/**,**/__pycache__/**,*.xml,*.cfg,coverage.xml

# Coverage report generado por pytest-cov
sonar.python.coverage.reportPaths=coverage.xml

# Encoding
sonar.sourceEncoding=UTF-8
