# Perfil Service - Reto 3
# Servicio consumidor de eventos y API REST para gestion de perfiles

spring.application.name=perfiles-service
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/}
spring.data.mongodb.database=db-perfiles
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin
spring.rabbitmq.listener.simple.acknowledge-mode=auto
server.port=${PERFILES_SERVICE_PORT:8083}
management.endpoints.web.exposure.include=health,info
logging.level.com.microservicios.perfiles_service=DEBUG
logging.level.org.springframework.amqp=DEBUG
